# Generated by Django 5.1.7 on 2025-04-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_hall_name_alter_movie_genre_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of the ticket in RUB', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('number_of_tickets', models.IntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.session')),
            ],
        ),
    ]
