# Generated by Django 5.2 on 2025-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0002_autoservice_alter_servicerepair_service_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='autoservice',
            name='car_brands',
            field=models.ManyToManyField(related_name='autoservices', to='carservice.carbrand'),
        ),
    ]
