# Generated by Django 5.2 on 2025-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0004_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerepair',
            name='duration',
            field=models.IntegerField(default=1, help_text='Время работы в часах'),
        ),
    ]
