# Generated by Django 5.2 on 2025-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0006_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='address',
            field=models.CharField(null=True),
        ),
    ]
